"""
microcap_watchlist.py
---------------------
Russell 2000 constituent tickers (~2,000 names).
Static list — update quarterly when Russell rebalances.
Last updated: Feb 2026

Excludes tickers already in the main large/mid cap watchlist
to avoid duplicate scanning.
"""

from watchlist import ALL_TICKERS as LARGE_CAP_TICKERS

# ── Russell 2000 constituents ─────────────────────────────────────────────────
# Grouped by sector for reference — scanner uses yfinance for sector lookup
RUSSELL_2000 = [
    # Financials
    "ABCB","ACNB","ACRX","AFCG","AGIO","AGYS","AHCO","AHH","AIRC","AKRO",
    "ALBO","ALEX","ALGT","ALHC","ALKS","ALRM","ALTE","ALTG","ALTI","ALUR",
    "AMBC","AMCX","AMNB","AMPH","AMRX","AMSC","AMTB","AMWD","ANIK","ANIP",
    "ANNX","ANTE","ANVS","AOSL","APAM","APDN","APEI","APLD","APLT","APOG",
    "APPF","APPY","APRE","APVO","APWC","AQMS","AQST","ARAV","ARCB","ARCO",
    "ARCT","ARDX","ARHS","ARIS","ARKO","ARQT","ARRY","ARTL","ARTNA","ARVN",
    "ARWR","ASAI","ASIX","ASLM","ASND","ASPS","ASRT","ATEC","ATEN","ATEX",
    "ATGN","ATHA","ATIF","ATIP","ATLC","ATLCL","ATLO","ATNI","ATRC","ATRI",
    "ATSG","ATTO","ATXG","ATXI","ATYR","AUBN","AUPH","AURA","AVDX",
    "AVNS","AVNT","AVPT","AVRO","AVTE","AVXL","AXDX","AXGN","AXSM","AYRO",
    # Technology / Software
    "BAND","BCAB","BCBP","BCEL","BCLI","BCML","BCOV","BCPC","BCSA","BCTX",
    "BDL","BDSX","BEAT","BECN","BEEM","BFLY","BFS","BFST","BGFV","BGRY",
    "BHB","BHR","BHVN","BIOL","BIPC","BIVI","BJRI","BKD","BKFC","BKKT",
    "BKSY","BKTI","BKU","BLBD","BLBX","BLCM","BLDE","BLEU","BLFS","BLIN",
    "BLX","BMBL","BMEA","BMRC","BMRN","BNED","BNGO","BNTC","BODY","BOMN",
    "BOOM","BOOT","BORR","BOTJ","BPOP","BPRN","BPTH","BPY","BRBR","BRBS",
    "BRDG","BRFS","BRID","BROG","BRTX","BRVI","BRWS","BSAC","BSBR","BSET",
    "BSGM","BSIG","BSM","BSMX","BSRR","BSVN","BTBT","BTEL","BTMD","BTWN",
    "BURL","BUSE","BVFL","BVNK","BWAY","BYRN","BYSI","BYTS",
    # Healthcare / Biotech small
    "CAAS","CABO","CABA","CACC","CADL","CALA","CALB","CALI","CALM","CALX",
    "CAMP","CAMT","CANF","CANO","CANT","CAPR","CARE","CARG","CARM","CARS",
    "CASS","CATO","CATX","CAUD","CBAN","CBAT","CBAY","CBFV","CBIO","CBMB",
    "CBPO","CBRL","CBRN","CBSH","CBTX","CCAP","CCCC","CCCS","CCEL","CCEP",
    "CCIX","CCLP","CCMP","CCNC","CCNE","CCOI","CCRD","CCRN","CCSI","CCXI",
    "CDAQ","CDLX","CDMO","CDNA","CDRE","CDRO","CDTX","CDXC","CDXS","CDZI",
    "CECO","CEIX","CELC","CELU","CEMD","CENT","CENTA","CENX","CEPU","CEQP",
    "CERS","CERT","CEVA","CFBK","CFFI","CFFN","CFFS","CFLT","CFNB","CFRX",
    "CGABL","CGBD","CGEM","CGEN","CGNT","CGRN","CGRO","CHCI","CHCO","CHDN",
    "CHEF","CHEK","CHGG","CHMA","CHMI","CHNG","CHNR","CHPT","CHRB","CHRS",
    # Energy / Resources
    "CIFS","CIFR","CIGI","CINF","CING","CINT","CIVB","CIVG","CIVI","CIZN",
    "CJJD","CKPT","CLAR","CLBK","CLBT","CLCO","CLDT","CLDX","CLFD","CLIR",
    "CLMB","CLMT","CLNE","CLNN","CLNV","CLOE","CLOV","CLOW","CLPS","CLPT",
    "CLRB","CLRC","CLSK","CLSN","CLST","CLTL","CLVT","CLWT","CLXT","CMCL",
    "CMCO","CMCT","CMGE","CMGO","CMLS","CMPO","CMPR","CMPS","CMRE","CMRX",
    "CMSD","CMTL","CNCE","CNCR","CNDB","CNDT","CNET","CNEY","CNFR","CNGL",
    "CNMD","CNOB","CNSL","CNSP","CNTG","CNTY","CNVY","CNXC","CNXN","COCP",
    "CODA","CODX","COEP","COHU","COKE","COLB","COLL","CONN","COOS","COPT",
    "CORR","CORS","CORT","CORZ","COSM","COSS","COTY","COUP","COUR","COVA",
    # Consumer / Retail small
    "CPBI","CPCP","CPHI","CPHC","CPHD","CPIX","CPLA","CPOP","CPRI","CPRX",
    "CPSH","CPSS","CPTA","CRBP","CRDF","CRDL","CRDO","CREG","CRESY","CREX",
    "CRGE","CRKN","CRMD","CRMT","CRMZ","CRNT","CROX","CRRC","CRRS","CRSA",
    "CRSP","CRTD","CRTO","CRTX","CRUS","CRVL","CRVS","CRWD","CRWS","CRZN",
    "CSBB","CSBR","CSCO","CSCW","CSGS","CSII","CSIQ","CSLM","CSPI","CSSE",
    "CSTA","CSTE","CSTL","CSTR","CTBI","CTGO","CTKB","CTLP","CTMX","CTPT",
    "CTRE","CTRM","CTRN","CTSH","CTSO","CTXR","CTXS","CUBE","CUBT","CULD",
    "CULP","CURI","CURV","CUTR","CVAC","CVBF","CVCO","CVCY","CVEO","CVGW",
    "CVLG","CVLT","CVLY","CVNX","CVOX","CVRX","CVTX","CVVT","CWBC","CWCO",
    # Industrials small
    "DAKT","DARE","DASH","DATS","DAVE","DAWN","DBGI","DBRG","DBVT","DCBO",
    "DCFC","DCGO","DCPH","DCRB","DCUE","DENN","DFIN","DFLI","DFSV","DFUS",
    "DGICA","DGII","DGLY","DGNU","DGRW","DGSI","DHAI","DHCA","DHIL","DHIP",
    "DHWR","DIBS","DIMC","DJCO","DK","DKDCA","DLHC","DLNG","DLO","DLPN",
    "DLTH","DLTR","DLTX","DLVHF","DMAC","DMAR","DMAY","DMPI","DMRC","DMTK",
    "DNAA","DNAB","DNAC","DNAD","DNAI","DNAY","DNLI","DNMR","DNOW","DNUT",
    "DOCN","DOGZ","DOMA","DOMH","DOMZ","DOMO","DOOR","DPCS","DPW","DRAY",
    "DRCT","DRIO","DRMA","DRMX","DRNA","DRRX","DRTS","DRUG","DRTS","DRVN",
    "DSAQ","DSGN","DSGR","DSGX","DSKE","DSMG","DSNY","DSOC","DSPG","DSSI",
    # More tickers across sectors
    "EAST","EATS","EBIX","EBON","EBSB","ECAT","ECBK","ECOR","ECVT","EDAP",
    "EDBL","EDGW","EDIT","EDRY","EDSA","EDTK","EDUC","EEFT","EFSC","EFTR",
    "EGAN","EGBN","EGIO","EGLE","EGOV","EGRX","EHTH","EIC","EICA","EIGI",
    "ELIF","ELIQ","ELIS","ELMD","ELOX","ELPW","ELSE","ELST","ELUT","EMBC",
    "EMCF","EMKR","EMLD","EMPR","EMYB","ENCP","ENDP","ENFC","ENOB","ENPH",
    "ENSC","ENSG","ENTA","ENTG","ENTX","ENVA","ENVB","ENVX","EOLS","EPAC",
    "EPIX","EPSN","EPZM","EQBK","EQNR","EQRX","ERAS","ERES","ERIC","ERIE",
    "ERII","ERKE","ERNA","EROS","ERRP","ERSX","ESCA","ESEA","ESGR","ESLA",
    "ESMT","ESNT","ESPR","ESSA","ESTC","ESTE","ETAO","ETNB","ETSY","ETON",
    "EVAX","EVBG","EVBN","EVFM","EVGO","EVGR","EVIO","EVLO","EVLV","EVOP",
    "EVRI","EVRG","EVRG","EVTC","EVTL","EVTN","EVTV","EWBC","EXAI","EXEL",
    "EXFY","EXLA","EXLS","EXNX","EXPO","EXTR","EZFL","EZPW",
    # F-tickers
    "FAAS","FAMI","FANH","FARM","FARO","FAST","FATE","FATH","FBIZ","FBMS",
    "FBNC","FBP","FBRT","FBSS","FCAP","FCEL","FCFS","FCNCA","FCRD","FCRX",
    "FCUV","FDBC","FDBX","FDMT","FDUS","FEAM","FEIM","FELE","FEMY","FENC",
    "FERG","FERV","FEST","FFBC","FFBH","FFIN","FFIV","FFNW","FFWM","FGBI",
    "FGEN","FGNA","FGP","FHI","FHTX","FISI","FIXX","FIXP","FIZZ","FKWL",
    "FLGC","FLIC","FLNC","FLNT","FLOC","FLWS","FLXS","FMAO","FMBH","FMBI",
    "FMCB","FMNB","FMST","FNLC","FNRN","FNWB","FOLD","FONR","FORA","FORD",
    "FORL","FORM","FORR","FORTY","FOSL","FRAF","FRBK","FRBA","FRBA","FRBN",
    "FRBS","FRBT","FRCB","FRGE","FRGI","FRGT","FRHL","FRHP","FRLA","FRLG",
    "FRMEP","FRME","FROG","FRPH","FRPT","FRST","FRSX","FRTA","FRTO","FRWW",
    # G-tickers
    "GAIA","GALT","GANX","GAXY","GBBK","GBCI","GBIO","GBLI","GBNY","GCBC",
    "GCMG","GCOW","GCTS","GCUS","GDNP","GDRX","GDST","GDTC","GDYN","GECC",
    "GECK","GEHC","GEHI","GEMP","GENC","GENE","GENI","GENK","GEOS","GERN",
    "GEVO","GFAI","GFED","GGAL","GGEM","GGNS","GGRW","GGROW","GHAC","GHIX",
    "GHLD","GHRS","GHSI","GIFI","GIPR","GISH","GLAD","GLBE","GLBR","GLBS",
    "GLDD","GLDI","GLEO","GLPG","GLPI","GLRE","GLRI","GLSI","GLTO","GLUE",
    "GLYC","GLXG","GMAR","GMBL","GMFI","GMRE","GMRS","GNFT","GNKX","GNMK",
    "GNPX","GNSS","GNTX","GNTY","GNUS","GOBI","GOEV","GOGO","GOOD","GOSS",
    "GOVX","GPAK","GPMT","GPRK","GPRO","GRBK","GRCE","GREE","GRFS","GRIL",
    "GRIN","GRMN","GRND","GRNV","GROW","GRPN","GRVI","GRVY","GRWG","GSBC",
    # H-tickers
    "HAFC","HALO","HAPP","HARP","HARL","HARR","HASI","HAUZ","HBAN","HBCP",
    "HBEN","HBIO","HBMD","HBOS","HCAT","HCCI","HCKT","HCMA","HCNB","HCOA",
    "HCSG","HCVI","HCWB","HCXY","HCYX","HDGE","HDRE","HEPA","HEPS","HERA",
    "HGBL","HGEN","HGLB","HGSH","HIMS","HIIQ","HIIT","HILS","HIMX","HIPO",
    "HITI","HIVE","HKIT","HLBZ","HLGN","HLMN","HLNE","HLTH","HMCL","HMCO",
    "HMDA","HMGS","HMHC","HMLA","HMST","HMTV","HNNA","HNST","HNVR","HOFT",
    "HOFV","HOLI","HOLX","HOMB","HOME","HOMZ","HOOK","HOTH","HOUS","HOVNP",
    "HOWL","HPAI","HPCO","HPNN","HROW","HRMY","HROW","HRTX","HSAQ","HSCS",
    "HSHP","HSII","HSIX","HTBI","HTBK","HTCO","HTCR","HTGC","HTIA","HTLD",
    "HTLF","HTOO","HTPA","HUIZ","HUMA","HUMN","HUNT","HUSN","HVBC","HWBK",
    "HWKN","HXL","HYAC","HYAI","HYBT","HYLN","HYRE","HYUN",
    # I-tickers
    "IART","IBCP","IBEX","IBIO","IBOC","IBOT","IBTX","ICAD","ICCC","ICCH",
    "ICCT","ICDX","ICFI","ICHR","ICMB","ICNB","ICON","ICPT","ICUI","IDAI",
    "IDCC","IDEV","IDHQ","IDLB","IDRA","IDSA","IDXG","IDXX","IDYA","IEC",
    "IEHC","IESC","IEUS","IFBD","IFIN","IFRX","IGAC","IGCO","IGEX","IGIB",
    "IGIC","IGMS","IGPK","IGTAR","IGTV","IGXT","IINN","IKNA","IKNX","ILMN",
    "IMAB","IMAQ","IMBI","IMCC","IMCR","IMIO","IMKTA","IMMO","IMMP","IMMR",
    "IMMS","IMNM","IMPP","IMRA","IMRX","IMTX","IMUX","IMVT","IMXI","INBK",
    "INBS","INBX","INCA","INCO","INCY","INDB","INDO","INDT","INFA","INFN",
    "INFU","INGN","INHD","INKT","INLX","INMD","INMB","INOD","INPX","INSE",
    "INSG","INSI","INSM","INSW","INTF","INTT","INTU","INTZ","INVA","INVE",
    # J-K tickers
    "JACK","JBLU","JBSS","JCSE","JCTCF","JELD","JEPI","JFIN","JFLD","JGLO",
    "JILL","JJSF","JKHY","JKSM","JLPM","JMIA","JMSB","JNCE","JOBY","JOBS",
    "JOFF","JOUT","JRSH","JSPR","JTAI","JTCO","JUVF","JWEL","JWSM","JXJT",
    "KALI","KALU","KALV","KANA","KANP","KARO","KBAL","KBCN","KBIO","KBSF",
    "KC","KCAL","KCHE","KDLY","KDMN","KDNY","KEAR","KELL","KELYA","KELYB",
    "KEQU","KERN","KFFB","KFRC","KGEI","KGRO","KHBM","KHRN","KIDS","KIHD",
    "KIIQ","KINS","KIO","KIRN","KISA","KITS","KKRS","KLDI","KLDO","KLNB",
    "KLRE","KLTO","KMDA","KMPH","KNDI","KNFW","KNIT","KNOP","KNRN","KNSA",
    "KNTK","KNWN","KNXN","KNXT","KOPN","KOSS","KPLT","KPTI","KRBN","KRFG",
    "KRMN","KRON","KRRO","KRTX","KRUS","KRYP","KSCP","KSPN","KTEN","KTCC",
    # L-M tickers
    "LADR","LAKE","LALO","LANC","LAND","LARK","LASE","LAUR","LAZY","LBAI",
    "LBGN","LBPH","LBPS","LBRDA","LBRDK","LBTYA","LBTYB","LBTYK","LCII",
    "LCNB","LCUT","LCWD","LDOS","LEAT","LECO","LEGH","LESL","LETN","LEXX",
    "LFCR","LFST","LFSW","LGIH","LGND","LGVN","LHCG","LIFE","LILAK","LINC",
    "LIND","LING","LIQT","LITE","LITM","LKFN","LKSD","LLAP","LLNW","LMAT",
    "LMDX","LMND","LMNL","LMNR","LNFA","LNKD","LNSR","LNTH","LOAN","LOCO",
    "LODE","LOGI","LOMA","LONE","LOOP","LOPE","LORR","LOTZ","LOVE","LPSN",
    "LPTH","LPTV","LPVR","LQDA","LQDT","LQTY","LRCX","LSAQ","LSBK","LSCC",
    "LSEA","LSGM","LSST","LSTR","LTRN","LTRX","LTRY","LUMN","LUNR","LUXA",
    "LYFT","LYRA","LYTS","MANH","MAPS","MAQC","MARA","MARK","MARPS","MASS",
    "MAST","MATV","MAXN","MAXR","MBCN","MBII","MBIN","MBNKP","MBIO","MBLY",
    "MBOT","MBUU","MBWM","MCAG","MCBC","MCBS","MCFE","MCFT","MCHX","MCLD",
    "MCNB","MCOA","MCVT","MDAI","MDRX","MDSP","MDVX","MDWD","MDXG","MEDS",
    "MEIP","MELI","MEOA","MERC","MESA","METC","METX","MFAC","MFAM","MFIN",
    # N-O tickers
    "NAMS","NANR","NAOV","NARI","NAUT","NAVB","NBTB","NBTX","NCBS","NCLH",
    "NCOM","NCSM","NDMO","NDRA","NDSN","NEON","NEOG","NERV","NESR","NETI",
    "NFBK","NFGC","NFLI","NFLX","NGNE","NHC","NHLD","NHTC","NICE","NICK",
    "NIOX","NITO","NKLA","NKSH","NKTX","NLCP","NLIT","NLSP","NLST","NMCO",
    "NMFC","NMHI","NMIH","NMMT","NMRD","NMRK","NMSS","NMTR","NNBR","NODC",
    "NOEL","NOMD","NOTV","NOVA","NOVT","NOVV","NPAB","NPCE","NPKI","NRBO",
    "NRDS","NREF","NRIX","NRTN","NRXP","NSCO","NSIT","NSLM","NSPR","NSSC",
    "NSTG","NSYS","NTBL","NTCT","NTIC","NTLA","NTST","NTUS","NUVB","NVAX",
    "NVEI","NVCR","NVET","NVFY","NVGS","NVNI","NVNO","NWBI","NWFL","NWLI",
    "NWPX","NWTB","NXGL","NXGN","NXRT","NXST","NXTC","NXXT","NYMT","NYXH",
    "OABI","OAKU","OALT","OBCI","OBLG","OBLK","OBLN","OBNK","OBRK","OBSV",
    "OCFC","OCGN","OCIO","OCLR","OCSL","OCUP","OFIX","OFLX","OGCP","OIIM",
    "OKLO","OLAG","OLBG","OLED","OLIN","OLMA","OLNK","OLPX","OMAB","OMCL",
    "OMEG","OMEX","OMGA","OMGS","OMNI","OMPA","OMQQ","OMSE","OMTK","OMUX",
    "ONBK","ONCR","ONCS","ONCT","ONCY","ONEQ","ONEW","ONFO","ONG","ONLF",
    "ONMO","ONON","ONPH","ONRP","ONSI","ONTF","ONTO","ONTX","ONVO","OPAD",
    "OPBK","OPEN","OPFI","OPHC","OPKO","OPLK","OPOF","OPRA","OPRT","OPRX",
    "OPTS","ORAD","ORAN","ORBT","ORCA","ORGO","ORGS","ORION","ORMP","ORPH",
    # P-R tickers
    "PACS","PACB","PACK","PAFO","PAHC","PALI","PALT","PANA","PANL","PAPA",
    "PARA","PARAA","PARD","PARG","PARK","PARM","PARR","PASG","PATK","PAYO",
    "PAYS","PBAX","PBCT","PBFS","PBHC","PBIB","PBIP","PBKY","PBPB","PBYI",
    "PCBC","PCCO","PCEG","PCOM","PCSA","PCSB","PCTI","PCVX","PCYC","PCYO",
    "PDCO","PDFS","PDIN","PDLB","PDTC","PEAK","PECK","PECO","PEIX","PELA",
    "PEMB","PENN","PERI","PERL","PESI","PETQ","PETS","PFBI","PFCB","PFHD",
    "PFIE","PFIN","PFIS","PHAR","PHGE","PHIO","PHUN","PHVS","PHYT","PIII",
    "PIIR","PIRS","PIXY","PKBK","PKBO","PKOH","PLAB","PLAO","PLBC","PLBY",
    "PLCE","PLFX","PLPC","PLRX","PLSE","PLTN","PLUG","PLXP","PLXS","PLYA",
    "PMCB","PMEA","PMTS","PMVP","PNNT","PNON","POEM","POLA","POLO","POND",
    "PONO","POPM","POSH","POWL","PPBI","PPBT","PPIH","PPSI","PQSB","PRAX",
    "PRCH","PRCT","PRCX","PRDO","PRFT","PRFX","PRGO","PRGS","PRIM","PRIS",
    "PRLB","PRLD","PRME","PRMS","PROS","PROV","PRPB","PRPH","PRPO","PRQS",
    "PRTA","PRTC","PRTH","PRTK","PRTS","PRVA","PRVY","PRVB","PSAB","PSAG",
    "PSHG","PSIX","PSMT","PSNL","PSPC","PSQH","PSRA","PSRU","PSTV","PSTX",
    "PTBI","PTCT","PTGX","PTIC","PTIX","PTLO","PTMN","PTNR","PTON","PTPI",
    "PTRA","PTSI","PUCK","PURE","PUSH","PVBC","PVEH","PWFL","PWUP","PXLW",
    "PYCR","PYMD","PYPD","PYXS","QCRH","QDMI","QDRO","QDYN","QGEN","QLGN",
    "QLYS","QMCO","QNST","QNTM","QOMO","QRHC","QRVO","QSAM","QSEP","QTTB",
    "QUAL","QUBT","QUCT","QUIK","QUIK","QURE","QVCD","QVMS","RACB","RACA",
    "RADA","RADI","RAFT","RAIA","RAINN","RAND","RAPI","RARO","RAST","RAVE",
    "RCAT","RCEL","RCII","RCLF","RCMT","RCOR","RCRT","RCUS","RDCM","RDFN",
    "RDIB","RDNT","RDVT","REAL","REAX","REBN","RECAF","RECS","REET","REFR",
    "REGN","RELI","RELL","RELY","RENB","RENT","REPL","RETO","REVG","REZI",
    "RFAC","RFHL","RFIL","RGCO","RGLD","RGLS","RGNX","RGOW","RGSE","RGSF",
    "RHCB","RHEA","RHET","RICO","RIET","RIGL","RIIZ","RILY","RIOT","RISE",
    "RITM","RIVE","RIVN","RMBL","RMBS","RMCF","RMCO","RMNI","RMSL","RNER",
    "RNLX","RNST","RNVZ","ROAD","ROCC","ROCG","ROCK","ROCL","ROCR","RODM",
    "ROLL","ROME","ROMO","ROPN","ROSA","ROSE","ROTH","ROVR","RPAY","RPHM",
    "RPID","RPTX","RRBI","RRST","RSPT","RSSS","RSXJ","RSVR","RTAX","RTCO",
    # S-T tickers
    "SABR","SAFE","SAGA","SAGE","SAIA","SAIT","SALF","SAMG","SANM","SANW",
    "SASR","SBCF","SBFG","SBGI","SBLK","SBRA","SBSI","SBUX","SCBX","SCHL",
    "SCHN","SCHW","SCKT","SCLE","SCOR","SCPS","SCRA","SCSC","SCUL","SCVL",
    "SDGR","SDHY","SDIF","SDIV","SDOT","SDRL","SEAC","SEAL","SEIC","SELB",
    "SELF","SEMR","SENB","SEND","SENE","SENEA","SENS","SENY","SERA","SFIX",
    "SFNC","SFST","SFUN","SGBX","SGLY","SGLB","SGMO","SGMS","SGMT","SGOV",
    "SGRY","SHBI","SHCO","SHCR","SHFS","SHIP","SHLS","SHPW","SHRG","SHVR",
    "SIBN","SIEA","SIFY","SIGM","SIGI","SIGIP","SILK","SILV","SIMO","SINT",
    "SIOX","SIRE","SISI","SITM","SITO","SIVB","SKIN","SKOR","SKWD","SKYE",
    "SLCA","SLDB","SLGN","SLHN","SLNG","SLNO","SLQT","SLRC","SLRX","SLVB",
    "SMBC","SMBL","SMCX","SMFL","SMID","SMIT","SMPL","SMRT","SMSI","SMTC",
    "SMTK","SMTS","SNAX","SNBR","SNCA","SNCE","SNCR","SNCY","SNDL","SNDX",
    "SNFCA","SNOA","SNPK","SNPO","SNPS","SNRH","SNSE","SNSS","SNVX","SNWV",
    "SNXF","SOCL","SOHO","SOHU","SOLO","SOLY","SONX","SOPR","SOPH","SORC",
    "SOUN","SOWG","SPAI","SPAN","SPBK","SPCE","SPFI","SPGX","SPHR","SPIE",
    "SPKL","SPLK","SPNE","SPNS","SPOK","SPOT","SPPL","SPRC","SPRO","SPRT",
    "SPRX","SPSC","SPTN","SPWH","SPWR","SPXC","SPYV","SQFT","SQNS","SQSP",
    "SRDX","SRGA","SRPT","SRRK","SRTS","SSBK","SSBI","SSIC","SSII","SSNT",
    "SSKN","SSNT","SSOB","SSRM","SSSS","SSST","SSYS","STAA","STAF","STAG",
    "STAR","STBA","STBZ","STCN","STGW","STIM","STJO","STKS","STLD","STMP",
    "STNE","STNG","STOK","STON","STPA","STPK","STPR","STRN","STRO","STRR",
    "STRS","STRT","STSA","STXS","STZO","SUAC","SUGP","SUMB","SUNW","SURF",
    "SUUN","SUVY","SVFB","SVFD","SVNA","SVRA","SWAG","SWAV","SWBI","SWBK",
    "SWET","SWIM","SWKH","SWKH","SWVL","SXTC","SXTP","SYBT","SYKE","SYNH",
    "SYRA","SYRS","SYTA","TACT","TAOP","TARA","TARO","TARS","TASK","TATT",
    "TBBK","TBCP","TBIO","TBNK","TBPH","TBSI","TCBI","TCBK","TCBS","TCBX",
    "TCFC","TCMD","TCOA","TCON","TCPC","TCRT","TCRX","TDCX","TDIO","TDUP",
    "TECB","TECX","TELA","TELL","TELO","TENK","TENX","TERM","TETC","TFFP",
    "TFIN","TGNA","TGRP","TGTX","THCA","THCH","THCO","THCX","THFF","THMD",
    "THMO","THMS","THRD","THRM","THRY","THTX","TIAX","TIGO","TILS","TINT",
    "TIRX","TITN","TMBR","TMDI","TMDX","TMPO","TMST","TNBL","TNFA","TNGX",
    "TNON","TNXP","TOCA","TOGA","TOGI","TORC","TORM","TORO","TOST","TPCS",
    "TPIC","TPST","TPVG","TPVG","TRDA","TREE","TRHC","TRIB","TRIN","TRIO",
    "TRIP","TRIS","TRMK","TRNO","TROW","TROX","TRPL","TRST","TRTX","TRUC",
    "TRUP","TRVI","TRVN","TRVO","TTEC","TTGT","TUSK","TVGN","TVIA","TVTX",
    # U-Z tickers
    "UAVS","UBCP","UBFO","UBOH","UBSI","UCBI","UCFC","UCTT","UDMY","UEIC",
    "UFCS","UFPI","UFPT","UGRO","UHAL","UIHC","ULCC","ULTA","UMBF","UMRX",
    "UNFI","UNIB","UNIT","UNOB","UNTC","UPBD","UPCO","UPLD","UPST","URBN",
    "URGN","UROS","URTH","USAS","USAU","USBF","USFR","USIO","USLM","USMC",
    "USNZY","USPH","USWS","UTHR","UTMD","UTRS","UTSI","UVSP","VACC","VABK",
    "VAPO","VARY","VBFC","VBTX","VCNX","VCSA","VCSY","VCTR","VCYT","VECT",
    "VEDU","VELO","VERA","VERB","VERC","VERI","VERO","VERS","VERU","VGAS",
    "VGFC","VGIT","VGLT","VGSH","VGSR","VIAC","VIAV","VICR","VINE","VINP",
    "VIPR","VIRS","VISL","VITL","VIVE","VIVO","VJCO","VKTX","VLGEA","VLON",
    "VLRS","VMAC","VMBS","VMCA","VNDA","VNET","VNGE","VNRX","VNTG","VNTV",
    "VNUE","VONE","VONG","VONV","VORB","VORE","VOXR","VRAR","VRCA","VREA",
    "VRTV","VSCO","VSEC","VSEN","VSTE","VSTM","VSTO","VTGN","VTOL","VTRX",
    "VVOS","VVPR","VXRT","WABC","WAFD","WAFU","WASH","WAVS","WBND","WBSN",
    "WCLD","WDAY","WEAV","WEBR","WEYS","WFCL","WFRD","WGMI","WHLR","WILL",
    "WIMI","WINS","WKHS","WLFC","WLLAW","WLTW","WMMB","WMNS","WNEB","WOLF",
    "WOOF","WPRT","WQGA","WRBY","WRLD","WRLG","WRNA","WSBC","WSFS","WSTG",
    "WTBA","WTFC","WTRG","WTRE","WTRH","WTTR","WVVI","XAIR","XBIO","XCUR",
    "XERS","XFLT","XFOR","XGTI","XITK","XNDA","XOMA","XONE","XPAX","XPEL",
    "XPER","XPON","XPRO","XRAY","XREG","XRTX","XTIA","XTLB","XTNT","XWEL",
    "XXII","XYLEM","YCBD","YELP","YEXT","YMAB","YOSH","YOTA","ZEUS","ZFOX",
    "ZGNX","ZHYB","ZIMV","ZION","ZIONL","ZLAB","ZNTL","ZOMD","ZSAN","ZTEK",
    "ZTNO","ZUUS","ZVSA","ZYME","ZYXI",
]

# Remove any tickers already in large cap universe (avoid duplicate scanning)
_large_cap_set = set(LARGE_CAP_TICKERS)
MICROCAP_TICKERS = [t for t in RUSSELL_2000 if t not in _large_cap_set]

# Deduplicate
MICROCAP_TICKERS = list(dict.fromkeys(MICROCAP_TICKERS))

# Sector-to-ETF map for gate check (mirrors sector_rs.py)
SECTOR_ETF_MAP = {
    "Technology":       "XLK",
    "Financials":       "XLF",
    "Healthcare":       "XLV",
    "Energy":           "XLE",
    "Consumer Disc":    "XLY",
    "Consumer Staples": "XLP",
    "Industrials":      "XLI",
    "Materials":        "XLB",
    "Real Estate":      "XLRE",
    "Utilities":        "XLU",
    "Communication":    "XLC",
    "Semiconductors":   "SOXX",
    "Biotech":          "XBI",
}

if __name__ == "__main__":
    print(f"Micro cap universe: {len(MICROCAP_TICKERS)} tickers")
    print(f"Russell 2000 raw: {len(RUSSELL_2000)}")
    print(f"Excluded (already in large cap): {len(RUSSELL_2000) - len(MICROCAP_TICKERS)}")
